name: Clang-Format Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and set up clang-format-20
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-20
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 100

      - name: Run formatting check script
        run: ./scripts/fmt_check.sh
